### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [Dioguinxz/0.5.1#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

Faltou o indicativo de qual página está ativa e o efeito de scale para quando o mouse do usuário passa por cima da tarefa. 

O primeiro ítem poderia ser obtido com o uso de uma classe extra com efeito de negrito e então a adição dessa classe dentro do arquivo .html que a página está ativa. 

```html
<style>
  .ativo {
    text-weight: bold;
  }
</style>

<a href="pendentes.html" class="ativo pendentes">Pendentes</a>
```

O segundo ítem pode ser obtido através do uso do `:hover` para o seu `p`.

```css
p {
  margin: 35px 35px;
  padding: 10px;
  background-color: #8FD14F;
  border-radius: 5px;  
  text-align: left; 
}

p:hover {
  transform: scale(1.1);
}
```

https://github.com/Dioguinxz/0.5.1/blob/6bf3571f2a7c561b5072a3def59c76b8fd029336/index.html#L17

Além disso, faltou completar a navegação do usuário. No seu arquivo index.html, o caminho para o pendentes está incorreto. Seu arquivo que representa os pendentes deve ser o `index.html`. 

```html
<a href="index.html" class="btn1">Pendentes</a>
```

**Nota:** 7

# Comentários

Notei que o seu código está muito mal indentado. No VS Code você pode aplicar a formação automaticamente seguindo esses passos:
1. CTRL + P para abrir o executor de comandos
2. Digite "> Format Document"
